type Product @model {
  id: ID!
  name: String!
  category: Category! @relation
  category1: Category! @relation
  createdAt: Date! @default(value: "Date.now")
  updatedAt: Date! @default(value: "Date.now")
}
